name: scottish_fold
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - jupyterlab
  - notebook
  - ipykernel
  - numpy
  - pandas
  - plotly
  - scipy
  - matplotlib
  - seaborn
  - geopandas
  - keplergl=0.3.7
  - scikit-learn
  - tqdm
  - dotenv
